/* MFL Centre — sample catalogue.
 *
 * This is example inventory so the storefront opens in a working state.
 * Replace SAMPLE_NOTES with your own listings (or load them from your
 * backend in app.js -> loadCatalogue()).
 *
 * tint  = hue used for the cover wash, 0-360
 * price = pence, so arithmetic never drifts
 *
 * There are deliberately no ratings or reviews in here. Reviews are only
 * ever written by people who bought the pack through the site; seeding
 * them would be a fake review, which the Digital Markets, Competition and
 * Consumers Act 2024 bans outright.
 */

const SUBJECTS = [
  { id: "biology", name: "Biology", tint: 138 },
  { id: "chemistry", name: "Chemistry", tint: 205 },
  { id: "physics", name: "Physics", tint: 268 },
  { id: "maths", name: "Maths", tint: 28 },
  { id: "economics", name: "Economics", tint: 178 },
  { id: "psychology", name: "Psychology", tint: 338 },
  { id: "computing", name: "Computing", tint: 232 },
  { id: "law", name: "Law", tint: 18 },
  { id: "medicine", name: "Medicine", tint: 355 },
  { id: "history", name: "History", tint: 42 },
];

const LEVELS = ["GCSE", "A-Level", "IB", "Undergraduate", "Postgraduate"];

const SAMPLE_NOTES = [
  {
    id: "chm-mech",
    title: "Reaction Mechanisms, Fully Drawn",
    subject: "chemistry",
    course: "CHEM20200",
    institution: "University of Bristol",
    level: "Undergraduate",
    pages: 96,
    format: "Typed PDF",
    price: 1150,
    updated: "Sep 2026",
    seller: { name: "Priya Nandakumar", grade: "First · 82%", since: "2024" },
    summary:
      "Every mechanism on the second-year organic paper, drawn arrow by arrow with the electron source labelled. Written after marking two years of tutorial sheets, so the common wrong arrows are called out where students actually draw them.",
    contents: [
      ["Arrow-pushing conventions and how marks are awarded", 4],
      ["Nucleophilic substitution: SN1 vs SN2 decision tree", 11],
      ["Elimination: E1, E2, E1cb and the Zaitsev traps", 24],
      ["Carbonyl additions and the tetrahedral intermediate", 38],
      ["Electrophilic aromatic substitution, directing effects", 54],
      ["Rearrangements examiners like: pinacol, Beckmann, Baeyer-Villiger", 68],
      ["40 past-paper mechanisms worked in full", 79],
    ],
    includes: [
      "96-page searchable PDF, A4, printer-friendly",
      "40 worked past-paper mechanisms with mark-scheme wording",
      "One-page revision poster of all reagent conditions",
    ],
  },
  {
    id: "bio-essay",
    title: "AQA Biology Paper 3 Essay Bank",
    subject: "biology",
    course: "AQA 7402/3",
    institution: "AQA specification",
    level: "A-Level",
    pages: 64,
    format: "PDF + Anki",
    price: 800,
    updated: "Aug 2026",
    seller: { name: "Tomás Requena", grade: "A* · 96%", since: "2023" },
    summary:
      "Twelve model essays for the 25-mark question, each mapped to the six topic areas an examiner looks for, plus the linking sentences that pull marks across modules.",
    contents: [
      ["How the 25-mark essay is actually marked", 3],
      ["Essay 1-4: cycles, transport, and gas exchange", 8],
      ["Essay 5-8: control, homeostasis, and the nervous system", 22],
      ["Essay 9-12: genetics, evolution and ecosystems", 36],
      ["Cross-topic linking sentence bank", 51],
      ["Timed practice plan for the last four weeks", 60],
    ],
    includes: [
      "12 full model essays, examiner-annotated",
      "Anki deck of 180 linking sentences",
      "Four-week revision timetable",
    ],
  },
  {
    id: "math-proofs",
    title: "Linear Algebra: Every Proof on the Paper",
    subject: "maths",
    course: "MATH0006",
    institution: "UCL",
    level: "Undergraduate",
    pages: 78,
    format: "Handwritten scan",
    price: 900,
    updated: "Jun 2026",
    seller: { name: "Wei Zhang", grade: "First · 88%", since: "2024" },
    summary:
      "Handwritten in fountain pen at 600 dpi. Each proof is stated, then rebuilt line by line with the step that carries the mark circled in red.",
    contents: [
      ["Vector spaces, subspaces, spanning sets", 2],
      ["Linear independence and bases", 14],
      ["Rank-nullity, with three proofs of the same theorem", 27],
      ["Eigenvalues, eigenvectors, diagonalisability", 41],
      ["Inner product spaces and Gram-Schmidt", 58],
      ["Proof-writing checklist for the exam", 74],
    ],
    includes: [
      "78 scanned pages, 600 dpi, OCR text layer included",
      "Red-pen annotations marking where credit is earned",
      "Printable proof-writing checklist",
    ],
  },
  {
    id: "econ-hl",
    title: "IB Economics HL Diagram Pack",
    subject: "economics",
    course: "IB HL Paper 1-3",
    institution: "IB Diploma",
    level: "IB",
    pages: 52,
    format: "Typed PDF",
    price: 750,
    updated: "Sep 2026",
    seller: { name: "Sofia Lindqvist", grade: "7/7 HL", since: "2024" },
    summary:
      "Every diagram the HL syllabus can ask for, drawn to scale with axes labelled the way the mark scheme wants, plus the two evaluation sentences that reliably earn the last band.",
    contents: [
      ["Drawing rules: axes, labels, and the marks they carry", 2],
      ["Micro: elasticities, market failure, intervention", 7],
      ["Macro: AD-AS, multiplier, Phillips curve", 21],
      ["Trade: tariffs, quotas, exchange rate diagrams", 34],
      ["Evaluation sentence bank by command term", 45],
    ],
    includes: [
      "52-page PDF with 68 exam-ready diagrams",
      "Evaluation sentence bank sorted by command term",
      "Paper 3 calculation walkthroughs",
    ],
  },
  {
    id: "med-neuro",
    title: "Neuroanatomy Flashcards, 612 Cards",
    subject: "medicine",
    course: "MBBS Year 2",
    institution: "King's College London",
    level: "Undergraduate",
    pages: 0,
    cards: 612,
    format: "Anki deck",
    price: 1400,
    updated: "Jul 2026",
    seller: { name: "Amara Okonkwo", grade: "Distinction", since: "2022" },
    summary:
      "Image-occlusion cards built on labelled tract diagrams and coronal sections. Cloze order follows the spotter exam, not the textbook, so recall matches how you are tested.",
    contents: [
      ["Cranial nerves: nuclei, course, lesions (118 cards)", 1],
      ["Ascending and descending tracts (94 cards)", 1],
      ["Brainstem cross-sections, occlusion cards (140 cards)", 1],
      ["Cerebral vasculature and stroke syndromes (86 cards)", 1],
      ["Cerebellum and basal ganglia circuits (98 cards)", 1],
      ["Spotter-style rapid recall (76 cards)", 1],
    ],
    includes: [
      "612-card Anki deck (.apkg), image occlusion enabled",
      "Suggested 6-week scheduling preset",
      "PDF of the source diagrams, unoccluded",
    ],
  },
  {
    id: "psy-cog",
    title: "Cognitive Psychology: Studies, Dates, Criticisms",
    subject: "psychology",
    course: "PSYC21000",
    institution: "University of Manchester",
    level: "Undergraduate",
    pages: 58,
    format: "Typed PDF",
    price: 650,
    updated: "May 2026",
    seller: { name: "Grace Whitfield", grade: "2:1 · 68%", since: "2025" },
    summary:
      "One table per topic: the study, the year, what it showed, and the two criticisms that get cited back at it. Built for essays where you need a counterpoint in the next sentence.",
    contents: [
      ["Attention: Broadbent to load theory", 3],
      ["Working memory: the model and its critics", 14],
      ["Long-term memory systems and amnesia cases", 25],
      ["Language processing and the modularity debate", 38],
      ["Essay planning grids for the six exam questions", 49],
    ],
    includes: [
      "58-page PDF with 40 study tables",
      "Six essay planning grids",
      "Reference list formatted in APA 7",
    ],
  },
  {
    id: "law-contract",
    title: "Contract Law Case Grid",
    subject: "law",
    course: "LAW1005",
    institution: "King's College London",
    level: "Undergraduate",
    pages: 44,
    format: "Typed PDF",
    price: 1000,
    updated: "Aug 2026",
    seller: { name: "Oliver Mensah", grade: "First · 79%", since: "2023" },
    summary:
      "116 cases on one grid: facts in a line, ratio in a line, and the principle it is cited for. Formatted to be readable in the two minutes you get per problem question.",
    contents: [
      ["Formation: offer, acceptance, certainty", 2],
      ["Consideration and promissory estoppel", 11],
      ["Terms, incorporation and exclusion clauses", 19],
      ["Vitiating factors: misrep, duress, mistake", 28],
      ["Discharge and remedies", 36],
      ["Problem question structure (IRAC worked twice)", 41],
    ],
    includes: [
      "116-case grid, sortable PDF",
      "Two fully worked IRAC problem answers",
      "Printable one-page remedies flowchart",
    ],
  },
  {
    id: "phys-thermo",
    title: "Thermodynamics Derivations, Step by Step",
    subject: "physics",
    course: "PHAS0024",
    institution: "UCL",
    level: "Undergraduate",
    pages: 71,
    format: "Typed PDF",
    price: 950,
    updated: "Apr 2026",
    seller: { name: "Wei Zhang", grade: "First · 88%", since: "2024" },
    summary:
      "Each of the standard results derived from the first law without skipping algebra, with the physical assumption stated at every line where one is made.",
    contents: [
      ["First law, exact and inexact differentials", 3],
      ["Maxwell relations, all four derived", 15],
      ["Heat engines, Carnot, and entropy", 29],
      ["Thermodynamic potentials and Legendre transforms", 44],
      ["Statistical link: partition function to free energy", 58],
    ],
    includes: [
      "71-page PDF, LaTeX-set",
      "Assumption checklist for each derivation",
      "18 past-paper questions with full solutions",
    ],
  },
  {
    id: "gcse-maths",
    title: "GCSE Higher Maths: Method Marks",
    subject: "maths",
    course: "Edexcel 1MA1",
    institution: "Edexcel specification",
    level: "GCSE",
    pages: 40,
    format: "Typed PDF",
    price: 500,
    updated: "Sep 2026",
    seller: { name: "Grace Whitfield", grade: "Grade 9", since: "2025" },
    summary:
      "The 30 questions that decide a grade 7 from a grade 9, each shown twice: the answer that gets full marks, and the near-miss that loses two.",
    contents: [
      ["Where method marks live in the mark scheme", 2],
      ["Algebra: the ten highest-value question types", 6],
      ["Geometry and trigonometry traps", 17],
      ["Ratio, proportion and rates of change", 26],
      ["Probability and statistics", 33],
    ],
    includes: [
      "40-page PDF with 30 paired worked examples",
      "Checklist of phrases that earn method marks",
    ],
  },
  {
    id: "cs-ds",
    title: "Data Structures Complexity Sheets",
    subject: "computing",
    course: "COMP0002",
    institution: "UCL",
    level: "Undergraduate",
    pages: 36,
    format: "PDF + code",
    price: 700,
    updated: "Jul 2026",
    seller: { name: "Oliver Mensah", grade: "First · 79%", since: "2023" },
    summary:
      "Time and space complexity for every structure on the module, with the Java implementation next to it and a note on when the average case stops being the case you get.",
    contents: [
      ["Arrays, dynamic arrays, amortised analysis", 2],
      ["Linked lists, stacks, queues, deques", 8],
      ["Trees: BST, AVL, red-black, heaps", 14],
      ["Hash tables, collision strategies, load factor", 24],
      ["Graphs: representations and traversal costs", 30],
    ],
    includes: [
      "36-page PDF cheat sheets",
      "Runnable Java reference implementations",
      "Big-O comparison poster, A3 printable",
    ],
  },
  {
    id: "hist-britain",
    title: "Britain 1918-1997: Timeline and Historiography",
    subject: "history",
    course: "HIST2043",
    institution: "University of Edinburgh",
    level: "Undergraduate",
    pages: 62,
    format: "Typed PDF",
    price: 750,
    updated: "Mar 2026",
    seller: { name: "Amara Okonkwo", grade: "First · 74%", since: "2022" },
    summary:
      "A dated spine of the century down the left, and the historians who argue about each stretch of it down the right, so essays can move from event to interpretation in one line.",
    contents: [
      ["1918-1939: settlement, depression, appeasement", 3],
      ["1939-1951: war economy and the Attlee settlement", 17],
      ["1951-1979: consensus and its critics", 29],
      ["1979-1997: Thatcherism and the historians", 44],
      ["Twelve essay questions with plans", 55],
    ],
    includes: [
      "62-page PDF with dated timeline spine",
      "Historiography column with 40 named positions",
      "Twelve planned essay answers",
    ],
  },
  {
    id: "psy-spss",
    title: "SPSS Walkthroughs for Psychology Stats",
    subject: "psychology",
    course: "PSYC10100",
    institution: "University of Manchester",
    level: "Undergraduate",
    pages: 48,
    format: "PDF + dataset",
    price: 600,
    updated: "Feb 2026",
    seller: { name: "Sofia Lindqvist", grade: "2:1 · 66%", since: "2024" },
    summary:
      "Screenshot-by-screenshot routes through every test on the lab report brief, ending each time with the sentence you paste into the results section.",
    contents: [
      ["Getting data in and coding variables", 2],
      ["t-tests, independent and paired", 9],
      ["One-way and factorial ANOVA", 18],
      ["Correlation and regression", 30],
      ["Reporting in APA 7: the exact sentences", 41],
    ],
    includes: [
      "48-page walkthrough PDF",
      "Practice dataset (.sav and .csv)",
      "APA results-sentence templates",
    ],
  },
];
