/* MFL Centre — sample catalogue.
 *
 * Example inventory so the storefront opens in a working state. Replace
 * SAMPLE_NOTES with your own listings, or load them from your backend in
 * app.js -> loadCatalogue().
 *
 * tint  = hue used for the cover wash, 0-360
 * price = pence, so arithmetic never drifts
 *
 * There are deliberately no ratings or reviews in here. Reviews are only
 * ever written by people who bought the pack through the site; seeding
 * them would be a fake review, which the Digital Markets, Competition and
 * Consumers Act 2024 bans outright.
 */

const SUBJECTS = [
  { id: "french", name: "French", tint: 218 },
  { id: "german", name: "German", tint: 40 },
  { id: "spanish", name: "Spanish", tint: 12 },
  { id: "italian", name: "Italian", tint: 140 },
  { id: "portuguese", name: "Portuguese", tint: 168 },
  { id: "mandarin", name: "Mandarin", tint: 352 },
  { id: "japanese", name: "Japanese", tint: 326 },
  { id: "russian", name: "Russian", tint: 258 },
];

const LEVELS = ["GCSE", "A-Level", "IB", "Undergraduate", "Postgraduate"];

const SAMPLE_NOTES = [
  {
    id: "fr-speaking",
    title: "A-Level French Speaking: Every Card Answered",
    subject: "french",
    course: "AQA 7652",
    institution: "AQA specification",
    level: "A-Level",
    pages: 72,
    format: "Typed PDF",
    price: 950,
    updated: "Sep 2026",
    seller: { name: "Amélie Fontaine", grade: "A* · 94%", since: "2024" },
    summary:
      "The stimulus card and the individual research project, both taken apart. Every sub-theme gets a worked answer, the follow-up questions examiners actually ask, and the phrases that buy you three seconds of thinking time without sounding rehearsed.",
    contents: [
      ["How the speaking exam is marked, band by band", 3],
      ["Reading the stimulus card in the 5 minutes you get", 9],
      ["Sub-themes 1-6: worked answers with follow-ups", 16],
      ["Sub-themes 7-12: worked answers with follow-ups", 34],
      ["Defending the IRP when the examiner pushes back", 52],
      ["Fillers, hedges and connectives that sound native", 63],
      ["Pronunciation traps that cost marks", 68],
    ],
    includes: [
      "72-page PDF, printable in A5 for revision cards",
      "24 worked card answers with examiner follow-ups",
      "One-page filler and connective sheet",
    ],
  },
  {
    id: "fr-gcse-vocab",
    title: "GCSE French Vocabulary, Theme by Theme",
    subject: "french",
    course: "AQA 8652",
    institution: "AQA specification",
    level: "GCSE",
    cards: 1240,
    pages: 0,
    format: "Anki deck",
    price: 650,
    updated: "Aug 2026",
    seller: { name: "Joseph Adeyemi", grade: "Grade 9", since: "2025" },
    summary:
      "Every word on the foundation and higher lists, split by theme and tagged by tier, with gender baked into the card so you never learn a noun without its article.",
    contents: [
      ["Identity and culture (312 cards)", 0],
      ["Local area, holiday and travel (288 cards)", 0],
      ["School and study (196 cards)", 0],
      ["Future aspirations and work (214 cards)", 0],
      ["International and global dimension (230 cards)", 0],
    ],
    includes: [
      "1,240-card Anki deck (.apkg), tagged foundation and higher",
      "Nouns carry their article so gender is learned with the word",
      "Printable CSV of the same list",
    ],
  },
  {
    id: "fr-film",
    title: "Au revoir les enfants: Scenes, Themes, Essays",
    subject: "french",
    course: "AQA 7652 Paper 2",
    institution: "AQA specification",
    level: "A-Level",
    pages: 46,
    format: "Typed PDF",
    price: 850,
    updated: "Jul 2026",
    seller: { name: "Amélie Fontaine", grade: "A* · 94%", since: "2024" },
    summary:
      "Malle's film read scene by scene with timecodes, so a quotation can be found in the ten seconds you have while planning. Eight model essays in French, each answering a real past question.",
    contents: [
      ["Occupation, Vichy and what Malle leaves unsaid", 2],
      ["Key scenes with timecodes and shot notes", 7],
      ["Julien and Bonnet: a friendship written in silences", 18],
      ["Complicity, class and the kitchen scene", 25],
      ["Eight model essays with examiner commentary", 31],
      ["Quotation bank in French with translations", 42],
    ],
    includes: [
      "46-page PDF with timecoded scene index",
      "Eight model essays written in French",
      "Quotation bank of 55 lines with translations",
    ],
  },
  {
    id: "fr-ib",
    title: "IB French B HL: Text Types and Register",
    subject: "french",
    course: "IB French B HL",
    institution: "IB Diploma",
    level: "IB",
    pages: 54,
    format: "Typed PDF",
    price: 900,
    updated: "Sep 2026",
    seller: { name: "Noor Haddad", grade: "7/7 HL", since: "2024" },
    summary:
      "Paper 1 is a register test wearing a writing task. Every text type the syllabus can set, with its conventions, its opening and closing formulas, and a model answer at level 7.",
    contents: [
      ["What the Paper 1 mark bands actually reward", 2],
      ["Blog, diary and personal message conventions", 8],
      ["Formal letter, report and proposal", 18],
      ["Speech, interview and article", 30],
      ["Switching register mid-task without slipping", 41],
      ["Paper 2 listening: the distractors to expect", 47],
    ],
    includes: [
      "54-page PDF covering all 11 text types",
      "Opening and closing formulas for each",
      "Six model answers marked at level 7",
    ],
  },
  {
    id: "de-cases",
    title: "German Cases: One Table, Every Ending",
    subject: "german",
    course: "AQA 7662",
    institution: "AQA specification",
    level: "A-Level",
    pages: 48,
    format: "Typed PDF",
    price: 700,
    updated: "Sep 2026",
    seller: { name: "Katrin Weiss", grade: "A* · 91%", since: "2023" },
    summary:
      "Adjective endings stop being guesswork once the weak, mixed and strong tables sit on one page in the order you actually need them. Built from the mistakes in two years of my own marked work.",
    contents: [
      ["The four cases and the questions that find them", 2],
      ["Adjective endings: weak, mixed and strong on one page", 9],
      ["Prepositions sorted by the case they take", 17],
      ["Two-way prepositions: motion versus position", 24],
      ["Word order, TMP, and where the verb really goes", 30],
      ["Separable and inseparable verbs", 38],
      ["120 drilled sentences with answers", 42],
    ],
    includes: [
      "48-page PDF, A4 and A5 layouts",
      "The one-page endings table, printable as a poster",
      "120 drill sentences with worked answers",
    ],
  },
  {
    id: "de-vorleser",
    title: "Der Vorleser: Quotations and Themes",
    subject: "german",
    course: "AQA 7662 Paper 2",
    institution: "AQA specification",
    level: "A-Level",
    pages: 44,
    format: "Typed PDF",
    price: 800,
    updated: "Jun 2026",
    seller: { name: "Katrin Weiss", grade: "A* · 91%", since: "2023" },
    summary:
      "Schlink's novel arranged for the exam rather than for reading: chapter summaries, the motifs examiners return to, and 60 quotations grouped by the argument they support.",
    contents: [
      ["Chapter summaries, part by part", 2],
      ["Hanna's illiteracy as motif and as excuse", 12],
      ["Guilt, shame and the second generation", 19],
      ["Narrative distance: why Michael tells it this way", 26],
      ["60 quotations grouped by argument", 32],
      ["Six essay plans against past questions", 40],
    ],
    includes: [
      "44-page PDF with chapter index",
      "60 quotations with translations and page references",
      "Six essay plans",
    ],
  },
  {
    id: "es-subjunctive",
    title: "The Spanish Subjunctive: When, and Why",
    subject: "spanish",
    course: "AQA 7692",
    institution: "AQA specification",
    level: "A-Level",
    pages: 56,
    format: "Typed PDF",
    price: 800,
    updated: "Sep 2026",
    seller: { name: "Diego Ramírez", grade: "A* · 96%", since: "2024" },
    summary:
      "Not a list of triggers to memorise but the logic underneath them, so an unfamiliar sentence still comes out right. Every trigger is paired with the indicative version so the difference is visible.",
    contents: [
      ["Why the subjunctive exists: the one idea", 2],
      ["Forming present, imperfect and perfect subjunctive", 7],
      ["Triggers of doubt, emotion and influence", 16],
      ["Time clauses: cuando, hasta que, en cuanto", 27],
      ["Si clauses and the conditional", 34],
      ["Ojalá, quizás and the ones that go either way", 41],
      ["80 drilled pairs, subjunctive against indicative", 46],
    ],
    includes: [
      "56-page PDF",
      "80 paired drill sentences with answers",
      "One-page trigger sheet",
    ],
  },
  {
    id: "es-lorca",
    title: "La casa de Bernarda Alba: Escenas y Citas",
    subject: "spanish",
    course: "AQA 7692 Paper 2",
    institution: "AQA specification",
    level: "A-Level",
    pages: 42,
    format: "Typed PDF",
    price: 800,
    updated: "May 2026",
    seller: { name: "Diego Ramírez", grade: "A* · 96%", since: "2024" },
    summary:
      "Lorca's play mapped act by act, with the colour and animal symbolism tracked across the whole text rather than listed once. Notes and essay plans written in Spanish.",
    contents: [
      ["Resumen por actos, con escenas clave", 2],
      ["Símbolos: el blanco, el verde, el agua, el caballo", 11],
      ["Los personajes y la jerarquía de la casa", 19],
      ["Honra, represión y la España de 1936", 26],
      ["70 citas ordenadas por tema", 32],
      ["Seis planes de ensayo", 38],
    ],
    includes: [
      "42-page PDF written in Spanish",
      "70 quotations indexed by theme",
      "Six essay plans in Spanish",
    ],
  },
  {
    id: "es-translation",
    title: "Spanish Translation: The Structures They Test",
    subject: "spanish",
    course: "AQA 7692 Paper 1",
    institution: "AQA specification",
    level: "A-Level",
    pages: 52,
    format: "PDF + dataset",
    price: 750,
    updated: "Aug 2026",
    seller: { name: "Noor Haddad", grade: "A · 88%", since: "2024" },
    summary:
      "Translation into Spanish is a narrow test wearing a wide coat: the same twenty structures come up every year. Each one gets the rule, the trap, and five sentences to drill it.",
    contents: [
      ["Ser and estar, decided in one question", 2],
      ["Por and para without the mnemonic", 9],
      ["Preterite against imperfect in narrative", 16],
      ["Pronoun order and where they attach", 24],
      ["Impersonal se and the passive", 32],
      ["100 drilled sentences with mark-scheme wording", 38],
    ],
    includes: [
      "52-page PDF",
      "100 drill sentences with accepted alternatives",
      "CSV of the sentence bank for your own flashcards",
    ],
  },
  {
    id: "it-year1",
    title: "First-Year Italian: The Grammar That Carries",
    subject: "italian",
    course: "ITAL1001",
    institution: "University of Leeds",
    level: "Undergraduate",
    pages: 68,
    format: "Handwritten scan",
    price: 850,
    updated: "Jun 2026",
    seller: { name: "Sofia Marchetti", grade: "First · 78%", since: "2025" },
    summary:
      "Handwritten across a first year of ab initio Italian and scanned at 600 dpi. The tenses are introduced in the order the course teaches them, with the exceptions written in the margin where I met them.",
    contents: [
      ["Articles, contractions and the prepositions they hide", 2],
      ["Presente: regular, then the verbs that aren't", 12],
      ["Passato prossimo against imperfetto", 24],
      ["Direct, indirect and combined pronouns", 38],
      ["Futuro, condizionale and the first conditional", 50],
      ["Congiuntivo: a first look", 60],
    ],
    includes: [
      "68 scanned pages at 600 dpi with an OCR text layer",
      "Margin notes marking the exceptions",
      "Verb tables for the 40 verbs the course assumes",
    ],
  },
  {
    id: "pt-variants",
    title: "Portuguese: Brazilian and European, Side by Side",
    subject: "portuguese",
    course: "PORT1010",
    institution: "University of Manchester",
    level: "Undergraduate",
    pages: 58,
    format: "Typed PDF",
    price: 800,
    updated: "Apr 2026",
    seller: { name: "Rita Carvalho", grade: "First · 80%", since: "2024" },
    summary:
      "One column each for the two standards, so you can learn either without accidentally mixing them. Covers the differences that change meaning, not just the ones that change accent.",
    contents: [
      ["Pronoun placement: the difference you hear first", 2],
      ["Gerund against a-plus-infinitive", 11],
      ["Você, tu, o senhor: address in both standards", 18],
      ["Vocabulary that diverges, with false friends", 27],
      ["Spelling after the 1990 agreement", 38],
      ["Listening notes: what to expect from each accent", 46],
    ],
    includes: [
      "58-page PDF in two-column comparison layout",
      "False-friend list with example sentences",
      "Notes on which variant each exam board expects",
    ],
  },
  {
    id: "zh-hsk4",
    title: "HSK 4: Characters, Measure Words, Patterns",
    subject: "mandarin",
    course: "HSK Level 4",
    institution: "Hanban syllabus",
    level: "Undergraduate",
    cards: 1010,
    pages: 0,
    format: "PDF + Anki",
    price: 1100,
    updated: "Jul 2026",
    seller: { name: "Li Wenjing", grade: "Distinction", since: "2023" },
    summary:
      "The 600 new characters grouped by radical rather than by textbook chapter, so the ones that look alike are learned apart. Sentence patterns come with the measure word already attached.",
    contents: [
      ["600 new characters grouped by radical", 0],
      ["Measure words, and the nouns that break the rules", 0],
      ["Resultative and directional complements", 0],
      ["把 and 被 sentences that examiners like", 0],
      ["Sentence patterns with drilled examples", 0],
    ],
    includes: [
      "1,010-card Anki deck with stroke-order diagrams",
      "PDF of the pattern list and measure-word tables",
      "Suggested eight-week schedule",
    ],
  },
  {
    id: "ja-n3",
    title: "JLPT N3 Grammar: 120 Patterns in Use",
    subject: "japanese",
    course: "JLPT N3",
    institution: "JLPT syllabus",
    level: "Undergraduate",
    pages: 64,
    format: "PDF + Anki",
    price: 1000,
    updated: "Aug 2026",
    seller: { name: "Li Wenjing", grade: "Pass, N2", since: "2023" },
    summary:
      "Each pattern gets the structure it attaches to, the register it belongs in, and the N4 pattern people confuse it with. Written while sitting N3, then corrected after sitting N2.",
    contents: [
      ["Patterns that attach to the plain form", 3],
      ["Patterns that attach to the て form", 16],
      ["Conditional family: と, ば, たら, なら", 28],
      ["Giving and receiving, and who is polite to whom", 38],
      ["Causative, passive and causative-passive", 46],
      ["Reading section: the connectives that carry meaning", 56],
    ],
    includes: [
      "64-page PDF with 120 patterns",
      "Anki deck of 120 example sentences with audio-ready fields",
      "Confusion table pairing each pattern with its N4 lookalike",
    ],
  },
  {
    id: "ru-motion",
    title: "Russian Verbs of Motion, Finally Clear",
    subject: "russian",
    course: "RUSS2010",
    institution: "University of Bristol",
    level: "Undergraduate",
    pages: 52,
    format: "Typed PDF",
    price: 900,
    updated: "Mar 2026",
    seller: { name: "Sofia Marchetti", grade: "First · 76%", since: "2025" },
    summary:
      "Unidirectional against multidirectional, then what each prefix does to both. The diagrams are the point: once you can see the motion, the pair you need stops being a coin toss.",
    contents: [
      ["Идти and ходить: the distinction, drawn", 2],
      ["The full pair list with aspect", 10],
      ["Prefixes по-, при-, у-, вы-, за-, пере-", 18],
      ["Motion verbs in the past: the tense trap", 32],
      ["Figurative uses that ignore the rules", 39],
      ["80 drills with answers", 44],
    ],
    includes: [
      "52-page PDF with motion diagrams",
      "Complete prefixed-pair reference table",
      "80 drill sentences with answers",
    ],
  },
];
